name: trinkinator
description: Ein Trinkspiel aus der Zukunft.
publish_to: 'none'
version: 3.0.2

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  flutter_riverpod:
  logger: ^2.0.2
  chat_bubbles: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/